---
- hosts: all
  become: yes

  # назначение переменных
  vars:
    # пользователь для запуска задач
    activemq_user: "activemq"
    # папка для установки activemq
    activemq_folder: "/opt/activemq"
    # порт activemq
    activemq_port: "8161"
    # memoryUsage
    memory_usage: "{{ ( ansible_memory_mb.real.total * 0.5 ) | int }} mb"
    # storeUsage
    store_usage: "115 gb"
    # tempUsage
    temp_usage: "48 gb"
    # ссылка для получения архива с activemq
    load_link: "http://archive.apache.org/dist/activemq/5.16.3/apache-activemq-5.16.3-bin.tar.gz"
    # путь скачивания архива с activemq
    load_to_file: "/tmp/pack.tar.gz"
    # временная папка
    temp_folder: "/tmp"
    # путь к распакованному во временной папке activemq
    unpacked_activemq: "{{ temp_folder }}/apache-activemq-5.16.3"
    # путь для environment JAVA_HOME
    java_home: "/usr/lib/jvm/java-1.8.0/"
    # путь для environment JRE_HOME
    jre_home: "/usr/lib/jvm/java-1.8.0/jre/"
    # путь к файлу конфигурации сервиса
    service_file: "/usr/lib/systemd/system/activemq.service"


  # задачи
  tasks:

    # проверка наличия файла конфигурации старого сервиса activemq
    - name: Check if the service file exists
      stat:
        path: "{{ service_file }}"
      register: srv_file

    # проверка существует ли папка с текущим activemq
    - name: Check if opt_activemq folder exists
      stat:
        path: "{{ activemq_folder }}"
      register: opt_activemq_folder

    # проверка существует ли папка с распакованным activemq в папке /tmp
    - name: Check if apache-activemq-5.16.3 folder exists
      stat:
        path: "{{ unpacked_activemq }}"
      register: unpack_folder

    # проверка существует ли скачанный архив activemq в папке /tmp
    - name: Check if loaded archive exists
      stat:
        path: "{{ load_to_file }}"
      register: archive_file

    # удаление папки apache-activemq-5.16.3 из папки /tmp, если она существует
    - name: Remove apache-activemq-5.16.3 folder
      file:
        path: "{{ unpacked_activemq }}"
        state: absent
      when: unpack_folder.stat.exists

    # удаление архива activemq из папки /tmp, если он существует
    - name: Remove archive
      file:
        path: "{{ load_to_file }}"
        state: absent
      when: archive_file.stat.exists

    # скачивание apache-activemq-5.16.3 в папку /tmp
    - name: Load ActiveMQ
      get_url:
        url: "{{ load_link }}"
        dest: "{{ load_to_file }}"

    # распаковывание архива в папку /tmp
    - name: Extract archive
      unarchive:
        src: "{{ load_to_file }}"
        dest: "{{ temp_folder }}"
        remote_src: yes

    # удаляем скачанный архив из папки /tmp
    - name: Remove archive
      file:
        path: "{{ load_to_file }}"
        state: absent

    # устанавка java
    - name: Install OpenJDK
      yum:
        name: java-1.8.0-openjdk-devel
        state: latest

    # создание environment variable JAVA_HOME
    - name: Export variable JAVA_HOME
      lineinfile:
        dest: /etc/profile
        regexp: '^export JAVA_HOME'
        line: 'export JAVA_HOME="{{ java_home }}"'
        state: present

    # создание environment variable JRE_HOME
    - name: Export variable JRE_HOME
      lineinfile:
        dest: /etc/profile
        regexp: '^export JRE_HOME'
        line: 'export JRE_HOME="{{ jre_home }}"'
        state: present
    
    # создание группы для пользователя, если используется не root
    - name: Create group for user
      group:
        name: "{{ activemq_user }}"
        system: yes
        state: present
      register: created_group
      when: 'activemq_user != "root"'
    
    # создание пользователя, если используется не root
    - name: Create user

      user:
        name: "{{ activemq_user }}"
        group: "{{ activemq_user }}"
        system: yes
        create_home: False
        state: present
      register: created_user
      when: 'activemq_user != "root"'

    # остановка сервиса activemq, если он существует
    - name: Stop old activemq.service
      service:
        name: activemq
        state: stopped
        enabled: no
      when: srv_file.stat.exists
      # вызов обработчика для перезапуска systemctl
      notify:
        - restart_systemctl

    # удаление старой папки activemq из папки /opt, если она существует
    - name: Remove {{ activemq_folder }} folder
      file:
        path: "{{ activemq_folder }}"
        state: absent
      when: opt_activemq_folder.stat.exists

    # перемещение распакованного activemq в папку /opt
    - name: Move move unpacked folder
      shell: "mv {{ unpacked_activemq }} {{ activemq_folder }}"

    # назначение прав на файлы activemq только для user
    - name: Change owner for activemq folder
      file:
        dest: "{{ activemq_folder }}"
        owner: "{{ activemq_user }}"
        group: "{{ activemq_user }}"
        mode: 0774
        recurse: yes

    # разрешение запуска исполняемого файла activemq
    - name: Allow binary execution
      file:
        dest: "{{ activemq_folder }}/bin/activemq"
        mode: a+x
      
    # замена activemq.xml из шаблона с учётом переменных
    - name: Replace activemq.xml
      template:
        src: templates/activemq.xml.j2
        dest: "{{ activemq_folder }}/conf/activemq.xml"
        owner: "{{ activemq_user }}"
        group: "{{ activemq_user }}"
        mode: 0774
      
    # замена jetty.xml из шаблона с учётом переменных
    - name: Replace jetty.xml
      template:
        src: templates/jetty.xml.j2
        dest: "{{ activemq_folder }}/conf/jetty.xml"
        owner: "{{ activemq_user }}"
        group: "{{ activemq_user }}"
        mode: 0774

    # удаление старой конфигурации сервиса, если она существует
    - name: Remove old activemq.service
      file:
        path: "{{ service_file }}"
        state: absent
      when: srv_file.stat.exists
      # вызов обработчика для перезапуска systemctl
      notify:
        - restart_systemctl
      
    # добавление новой конфигурации сервиса
    - name: Adding new activemq.service
      template:
        src: templates/activemq.service.j2
        dest: "{{ service_file }}"
        owner: "root"
        mode: 0644
      # вызов обработчика для перезапуска systemctl
      notify:
        - restart_systemctl

    # сервиса activemq и разрешение автозапуска при загрузке
    - name: Run a new service and set autorun on boot
      systemd:
        name: activemq
        state: restarted
        enabled: yes


  # обработчики
  handlers:
    # обработчик для перезапуска systemctl (помогает системе узнать об обновлении сервисов)
    - name: restart_systemctl
      shell: 
        cmd: "systemctl daemon-reload && systemctl reset-failed"
        chdir: /usr/lib/systemd/system/
