---

# проверка наличия файла конфигурации старого сервиса activemq
- name: Check if the service file exists
  stat:
    path: "{{ service_file }}"
  register: srv_file

# остановить плейбук если сервис существует
- name: Stop if service exists
  meta: end_play
  when: srv_file.stat.exists

# проверка существует ли папка с текущим activemq
- name: Check if opt_activemq folder exists
  stat:
    path: "{{ activemq_folder }}"
  register: opt_activemq_folder

# проверка существует ли папка с распакованным activemq в папке /tmp
- name: Check if apache-activemq-5.16.3 folder exists
  stat:
    path: "{{ unpacked_activemq }}"
  register: unpack_folder

# проверка существует ли скачанный архив activemq в папке /tmp
- name: Check if loaded archive exists
  stat:
    path: "{{ load_to_file }}"
  register: archive_file
